// This file is automatically generated as part of the build process

export const version = {
    version: "3.0.1-beta0191",
    commitInfo: "Branch.develop.Sha.96eae76377247bfd8187177200af8a85006a72ce",
    commitDate: "2025-09-28",
    commitHash: "96eae76377247bfd8187177200af8a85006a72ce",
    informationalVersion: "3.0.1-beta.191+Branch.develop.Sha.96eae76377247bfd8187177200af8a85006a72ce",
    buildDateUtc: new Date(Date.UTC(2025, 8, 28, 14, 31, 36))
}
